name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate SQL files exist
        run: |
          test -f docker/init/01_schema.sql
          test -f docker/init/02_views.sql
